[profile.default]
src = 'src'
out = 'out'
solc_version = '0.8.24'
via_ir = false
use_literal_content = true

# Enables or disables the optimizer
# The number of optimizer runs
optimizer = true
optimizer_runs = 200
gas_price = 30_000_000_000
block_base_fee_per_gas = 25_000_000_000

block_number = 0
block_timestamp = 1600000000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[rpc_endpoints]
linea = "${LINEA_RPC_URL}"

